//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/arall/PatchManager/src/PatchManager.Core/SassyPatchGrammar\sassy_parser.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SassyPatchGrammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Isassy_parserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class sassy_parserBaseListener : Isassy_parserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.patch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPatch([NotNull] sassy_parser.PatchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.patch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPatch([NotNull] sassy_parser.PatchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_statement([NotNull] sassy_parser.Top_level_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_statement([NotNull] sassy_parser.Top_level_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.import_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_declaration([NotNull] sassy_parser.Import_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.import_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_declaration([NotNull] sassy_parser.Import_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_decl([NotNull] sassy_parser.Var_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_decl([NotNull] sassy_parser.Var_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.stage_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage_def([NotNull] sassy_parser.Stage_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.stage_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage_def([NotNull] sassy_parser.Stage_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.function_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_def([NotNull] sassy_parser.Function_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.function_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_def([NotNull] sassy_parser.Function_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.mixin_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMixin_def([NotNull] sassy_parser.Mixin_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.mixin_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMixin_def([NotNull] sassy_parser.Mixin_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_conditional([NotNull] sassy_parser.Top_level_conditionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_conditional([NotNull] sassy_parser.Top_level_conditionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_else([NotNull] sassy_parser.Top_level_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_else([NotNull] sassy_parser.Top_level_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_else_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_else_else([NotNull] sassy_parser.Top_level_else_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_else_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_else_else([NotNull] sassy_parser.Top_level_else_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_else_if([NotNull] sassy_parser.Top_level_else_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_else_if([NotNull] sassy_parser.Top_level_else_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.selection_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection_block([NotNull] sassy_parser.Selection_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.selection_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection_block([NotNull] sassy_parser.Selection_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.attributed_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributed_selector([NotNull] sassy_parser.Attributed_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.attributed_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributed_selector([NotNull] sassy_parser.Attributed_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>require_mod</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequire_mod([NotNull] sassy_parser.Require_modContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>require_mod</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequire_mod([NotNull] sassy_parser.Require_modContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>require_not_mod</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequire_not_mod([NotNull] sassy_parser.Require_not_modContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>require_not_mod</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequire_not_mod([NotNull] sassy_parser.Require_not_modContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>run_at_stage</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRun_at_stage([NotNull] sassy_parser.Run_at_stageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>run_at_stage</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRun_at_stage([NotNull] sassy_parser.Run_at_stageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_element([NotNull] sassy_parser.Sel_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_element([NotNull] sassy_parser.Sel_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_ruleset</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_ruleset([NotNull] sassy_parser.Sel_rulesetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_ruleset</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_ruleset([NotNull] sassy_parser.Sel_rulesetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_child</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_child([NotNull] sassy_parser.Sel_childContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_child</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_child([NotNull] sassy_parser.Sel_childContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_add_element([NotNull] sassy_parser.Sel_add_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_add_element([NotNull] sassy_parser.Sel_add_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_class([NotNull] sassy_parser.Sel_classContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_class([NotNull] sassy_parser.Sel_classContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_name([NotNull] sassy_parser.Sel_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_name([NotNull] sassy_parser.Sel_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_intersection</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_intersection([NotNull] sassy_parser.Sel_intersectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_intersection</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_intersection([NotNull] sassy_parser.Sel_intersectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_everything([NotNull] sassy_parser.Sel_everythingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_everything([NotNull] sassy_parser.Sel_everythingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_without_class([NotNull] sassy_parser.Sel_without_classContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_without_class([NotNull] sassy_parser.Sel_without_classContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_without_name([NotNull] sassy_parser.Sel_without_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_without_name([NotNull] sassy_parser.Sel_without_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_combination</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_combination([NotNull] sassy_parser.Sel_combinationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_combination</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_combination([NotNull] sassy_parser.Sel_combinationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_sub</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_sub([NotNull] sassy_parser.Sel_subContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_sub</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_sub([NotNull] sassy_parser.Sel_subContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ruleset_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleset_selector([NotNull] sassy_parser.Ruleset_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ruleset_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleset_selector([NotNull] sassy_parser.Ruleset_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>combination_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCombination_selector([NotNull] sassy_parser.Combination_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>combination_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCombination_selector([NotNull] sassy_parser.Combination_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithout_name([NotNull] sassy_parser.Without_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithout_name([NotNull] sassy_parser.Without_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sub_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSub_selector([NotNull] sassy_parser.Sub_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sub_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSub_selector([NotNull] sassy_parser.Sub_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>class_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_selector([NotNull] sassy_parser.Class_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>class_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_selector([NotNull] sassy_parser.Class_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithout_class([NotNull] sassy_parser.Without_classContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithout_class([NotNull] sassy_parser.Without_classContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] sassy_parser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] sassy_parser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_element([NotNull] sassy_parser.Add_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_element([NotNull] sassy_parser.Add_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEverything([NotNull] sassy_parser.EverythingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEverything([NotNull] sassy_parser.EverythingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>intersection_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntersection_selector([NotNull] sassy_parser.Intersection_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>intersection_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntersection_selector([NotNull] sassy_parser.Intersection_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] sassy_parser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] sassy_parser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.selector_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector_body([NotNull] sassy_parser.Selector_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.selector_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector_body([NotNull] sassy_parser.Selector_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.selector_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector_statement([NotNull] sassy_parser.Selector_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.selector_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector_statement([NotNull] sassy_parser.Selector_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_level_conditional([NotNull] sassy_parser.Sel_level_conditionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_level_conditional([NotNull] sassy_parser.Sel_level_conditionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_level_else([NotNull] sassy_parser.Sel_level_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_level_else([NotNull] sassy_parser.Sel_level_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_else_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_level_else_else([NotNull] sassy_parser.Sel_level_else_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_else_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_level_else_else([NotNull] sassy_parser.Sel_level_else_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_level_else_if([NotNull] sassy_parser.Sel_level_else_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_level_else_if([NotNull] sassy_parser.Sel_level_else_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.set_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_value([NotNull] sassy_parser.Set_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.set_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_value([NotNull] sassy_parser.Set_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.delete_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelete_value([NotNull] sassy_parser.Delete_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.delete_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelete_value([NotNull] sassy_parser.Delete_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.merge_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMerge_value([NotNull] sassy_parser.Merge_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.merge_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMerge_value([NotNull] sassy_parser.Merge_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>element_key_field</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement_key_field([NotNull] sassy_parser.Element_key_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>element_key_field</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement_key_field([NotNull] sassy_parser.Element_key_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>string_key_field</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_key_field([NotNull] sassy_parser.String_key_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>string_key_field</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_key_field([NotNull] sassy_parser.String_key_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>number_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_indexor([NotNull] sassy_parser.Number_indexorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>number_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_indexor([NotNull] sassy_parser.Number_indexorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>element_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement_indexor([NotNull] sassy_parser.Element_indexorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>element_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement_indexor([NotNull] sassy_parser.Element_indexorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>class_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_indexor([NotNull] sassy_parser.Class_indexorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>class_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_indexor([NotNull] sassy_parser.Class_indexorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>string_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_indexor([NotNull] sassy_parser.String_indexorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>string_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_indexor([NotNull] sassy_parser.String_indexorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>implicit_add</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicit_add([NotNull] sassy_parser.Implicit_addContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>implicit_add</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicit_add([NotNull] sassy_parser.Implicit_addContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>implicit_subtract</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicit_subtract([NotNull] sassy_parser.Implicit_subtractContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>implicit_subtract</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicit_subtract([NotNull] sassy_parser.Implicit_subtractContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>implicit_multiply</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicit_multiply([NotNull] sassy_parser.Implicit_multiplyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>implicit_multiply</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicit_multiply([NotNull] sassy_parser.Implicit_multiplyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>implicit_divide</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicit_divide([NotNull] sassy_parser.Implicit_divideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>implicit_divide</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicit_divide([NotNull] sassy_parser.Implicit_divideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>normal</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNormal([NotNull] sassy_parser.NormalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>normal</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNormal([NotNull] sassy_parser.NormalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>not_equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_equal_to([NotNull] sassy_parser.Not_equal_toContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>not_equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_equal_to([NotNull] sassy_parser.Not_equal_toContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_reference([NotNull] sassy_parser.Variable_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_reference([NotNull] sassy_parser.Variable_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqual_to([NotNull] sassy_parser.Equal_toContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqual_to([NotNull] sassy_parser.Equal_toContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>indexor</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexor([NotNull] sassy_parser.IndexorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>indexor</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexor([NotNull] sassy_parser.IndexorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr([NotNull] sassy_parser.OrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr([NotNull] sassy_parser.OrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>value_reference</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_reference([NotNull] sassy_parser.Value_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>value_reference</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_reference([NotNull] sassy_parser.Value_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lesser_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLesser_than_equal([NotNull] sassy_parser.Lesser_than_equalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lesser_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLesser_than_equal([NotNull] sassy_parser.Lesser_than_equalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>subtraction</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubtraction([NotNull] sassy_parser.SubtractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>subtraction</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubtraction([NotNull] sassy_parser.SubtractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>positive</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositive([NotNull] sassy_parser.PositiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>positive</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositive([NotNull] sassy_parser.PositiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>simple_call</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_call([NotNull] sassy_parser.Simple_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>simple_call</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_call([NotNull] sassy_parser.Simple_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivision([NotNull] sassy_parser.DivisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivision([NotNull] sassy_parser.DivisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>negative</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegative([NotNull] sassy_parser.NegativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>negative</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegative([NotNull] sassy_parser.NegativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>not</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot([NotNull] sassy_parser.NotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>not</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot([NotNull] sassy_parser.NotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lesser_than</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLesser_than([NotNull] sassy_parser.Lesser_thanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lesser_than</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLesser_than([NotNull] sassy_parser.Lesser_thanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>member_call</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_call([NotNull] sassy_parser.Member_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>member_call</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_call([NotNull] sassy_parser.Member_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>greater_than</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGreater_than([NotNull] sassy_parser.Greater_thanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>greater_than</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGreater_than([NotNull] sassy_parser.Greater_thanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd([NotNull] sassy_parser.AndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd([NotNull] sassy_parser.AndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sub_sub_expression</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSub_sub_expression([NotNull] sassy_parser.Sub_sub_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sub_sub_expression</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSub_sub_expression([NotNull] sassy_parser.Sub_sub_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>multiplication</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplication([NotNull] sassy_parser.MultiplicationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multiplication</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplication([NotNull] sassy_parser.MultiplicationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>remainder</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemainder([NotNull] sassy_parser.RemainderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>remainder</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemainder([NotNull] sassy_parser.RemainderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>greater_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGreater_than_equal([NotNull] sassy_parser.Greater_than_equalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>greater_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGreater_than_equal([NotNull] sassy_parser.Greater_than_equalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ternary</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernary([NotNull] sassy_parser.TernaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ternary</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernary([NotNull] sassy_parser.TernaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>addition</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddition([NotNull] sassy_parser.AdditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addition</c>
	/// labeled alternative in <see cref="sassy_parser.sub_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddition([NotNull] sassy_parser.AdditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>value_deletion</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_deletion([NotNull] sassy_parser.Value_deletionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>value_deletion</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_deletion([NotNull] sassy_parser.Value_deletionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boolean_true</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_true([NotNull] sassy_parser.Boolean_trueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boolean_true</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_true([NotNull] sassy_parser.Boolean_trueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boolean_false</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_false([NotNull] sassy_parser.Boolean_falseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boolean_false</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_false([NotNull] sassy_parser.Boolean_falseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>number_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber_value([NotNull] sassy_parser.Number_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>number_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber_value([NotNull] sassy_parser.Number_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>string_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_value([NotNull] sassy_parser.String_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>string_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_value([NotNull] sassy_parser.String_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>none</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNone([NotNull] sassy_parser.NoneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>none</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNone([NotNull] sassy_parser.NoneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>list_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_value([NotNull] sassy_parser.List_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>list_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_value([NotNull] sassy_parser.List_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>object_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_value([NotNull] sassy_parser.Object_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>object_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_value([NotNull] sassy_parser.Object_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] sassy_parser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] sassy_parser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.list_values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_values([NotNull] sassy_parser.List_valuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.list_values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_values([NotNull] sassy_parser.List_valuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObj([NotNull] sassy_parser.ObjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObj([NotNull] sassy_parser.ObjContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.obj_values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObj_values([NotNull] sassy_parser.Obj_valuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.obj_values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObj_values([NotNull] sassy_parser.Obj_valuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>literal_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral_key([NotNull] sassy_parser.Literal_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>literal_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral_key([NotNull] sassy_parser.Literal_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>string_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_key([NotNull] sassy_parser.String_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>string_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_key([NotNull] sassy_parser.String_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_list([NotNull] sassy_parser.Argument_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_list([NotNull] sassy_parser.Argument_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>named_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamed_argument([NotNull] sassy_parser.Named_argumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>named_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamed_argument([NotNull] sassy_parser.Named_argumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unnamed_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnnamed_argument([NotNull] sassy_parser.Unnamed_argumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unnamed_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnnamed_argument([NotNull] sassy_parser.Unnamed_argumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.arg_decl_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg_decl_list([NotNull] sassy_parser.Arg_decl_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.arg_decl_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg_decl_list([NotNull] sassy_parser.Arg_decl_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>argument_without_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_without_default([NotNull] sassy_parser.Argument_without_defaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>argument_without_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_without_default([NotNull] sassy_parser.Argument_without_defaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>argument_with_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_with_default([NotNull] sassy_parser.Argument_with_defaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>argument_with_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_with_default([NotNull] sassy_parser.Argument_with_defaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_body([NotNull] sassy_parser.Function_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_body([NotNull] sassy_parser.Function_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.function_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_statement([NotNull] sassy_parser.Function_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.function_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_statement([NotNull] sassy_parser.Function_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFn_level_conditional([NotNull] sassy_parser.Fn_level_conditionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFn_level_conditional([NotNull] sassy_parser.Fn_level_conditionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFn_level_else([NotNull] sassy_parser.Fn_level_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFn_level_else([NotNull] sassy_parser.Fn_level_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_else_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFn_level_else_else([NotNull] sassy_parser.Fn_level_else_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_else_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFn_level_else_else([NotNull] sassy_parser.Fn_level_else_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFn_level_else_if([NotNull] sassy_parser.Fn_level_else_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFn_level_else_if([NotNull] sassy_parser.Fn_level_else_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFn_return([NotNull] sassy_parser.Fn_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFn_return([NotNull] sassy_parser.Fn_returnContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace SassyPatchGrammar
