---@meta
-- AUTO-GENERATED by the pm-stubs skill - do not edit by hand.
-- Source: ksp2redux/Assets/Modules/PatchManager/Runtime/LuaPatching/Builtin/PatchManagerCore.cs
-- Source: ksp2redux/Assets/Modules/PatchManager/Runtime/LuaPatching/Builtin/JsonModule.cs
-- Source: ksp2redux/Assets/Modules/PatchManager/Runtime/LuaPatching/Stage.cs
-- Source: ksp2redux/Assets/Modules/PatchManager/Runtime/LuaPatching/LuaPatch.cs
-- Source: ksp2redux/Assets/Modules/PatchManager/Runtime/LuaPatching/Universe.cs

---The PatchManager Lua library, exposed to scripts as the global `PM`.
---@class PatchManagerCore
---@field JSON GenericLuaModule
---@field Parts PartsLuaModule
---@field Resources ResourcesLuaModule
---@field Missions MissionsLuaModule
---@field Planets PlanetsLuaModule
---@field Science ScienceLuaModule
PatchManagerCore = {}

---Registers a patch that runs against every asset under the given addressables label.
---@param converter string The name of the converter to use, as registered via ConverterAttribute.
---@param label string The addressables label whose assets to patch.
---@param method fun(value: any): string? The patch callback. Returns `"remove"` to delete the asset, `nil` to keep it.
---@return LuaPatch patch The registered patch, suitable for chaining (for example LuaPatch.OnStage).
---@error Thrown when converter is not registered, or when method is nil.
function PatchManagerCore:PatchAll(converter, label, method) end

---Registers a patch that runs against assets under the given label whose name matches name.
---@param converter string The name of the converter to use, as registered via ConverterAttribute.
---@param label string The addressables label to patch.
---@param name string The addressables address pattern to match.
---@param method fun(value: any): string? The patch callback. Returns `"remove"` to delete the asset, `nil` to keep it.
---@return LuaPatch patch The registered patch, suitable for chaining (for example LuaPatch.OnStage).
---@error Thrown when converter is not registered, or when method is nil.
function PatchManagerCore:Patch(converter, label, name, method) end

---Queues a brand-new asset for creation under the given label and address.
---@param converter string The name of the converter that will serialize newObject to JSON.
---@param label string The addressables label to tag the new asset with.
---@param name string The asset's addressables address (globally unique).
---@param newObject any The Lua-facing value for the new asset.
---@error Thrown when converter is not registered.
function PatchManagerCore:New(converter, label, name, newObject) end

---Creates a named stage that runs after the most recent implicit stage from the same host mod.
---@param name string The stage name (registered as `"modId:name"`).
---@return Stage stage The created stage, suitable for chaining (for example Stage.Before / Stage.After).
function PatchManagerCore:ImplicitStage(name) end

---Creates a named stage that runs after the last implicit stage of the entire mod load order.
---@param name string The stage name (registered as `"modId:name"`).
---@return Stage stage The created stage, suitable for chaining (for example Stage.Before / Stage.After).
function PatchManagerCore:GlobalStage(name) end

---Creates a named stage with no implicit ordering; callers must declare any required relations explicitly.
---@param name string The stage name (registered as `"modId:name"`).
---@return Stage stage The created stage, suitable for chaining (for example Stage.Before / Stage.After).
function PatchManagerCore:Stage(name) end

---Returns whether the mod with the given ID is loaded.
---@param modId string The mod ID to test.
---@return boolean loaded True if the mod is loaded, false otherwise.
function PatchManagerCore:Loaded(modId) end

---Lua module exposed under the global `J` namespace, providing helpers for constructing JSON literals
---that MoonSharp's auto-conversion does not produce.
---@class JsonModule
JsonModule = {}

---Returns an empty JSON array as a JsonUserData.
---@return JsonUserData value A JsonUserData wrapping an empty `JArray`.
function JsonModule.Empty() end

---Wraps the first argument as an integer JSON value, forcing the integer slot type.
---@param value number The value cast to a number and truncated to a long.
---@return JsonUserData value A JsonUserData wrapping a `JValue` of integer type.
function JsonModule.Int(value) end

---A patching stage with optional ordering constraints relative to other stages.
---@class Stage
---@field RunsBefore string[] Stage names this stage must run before.
---@field RunsAfter string[] Stage names this stage must run after.
Stage = {}

---Adds each given stage name to RunsBefore and returns this stage for chaining.
---@param ... string The stage names this stage should run before.
---@return Stage self This stage.
function Stage:Before(...) end

---Adds each given stage name to RunsAfter and returns this stage for chaining.
---@param ... string The stage names this stage should run after.
---@return Stage self This stage.
function Stage:After(...) end

---A registered patch operation: which converter, which addressables target, what callback to run, and at which stage.
---@class LuaPatch
---@field ConverterInstance any The converter that produces the Lua value the patch operates on and serializes the result back to JSON.
---@field PatchMethod fun(value: any): string? The user-supplied callback that runs against each matched asset.
---@field Label string The addressables label whose assets this patch targets.
---@field Name string? The addressables address pattern this patch targets, or `nil` to match every asset in Label.
---@field Stage string The stage name that orders this patch relative to others. Defaults to the host mod's ID.
LuaPatch = {}

---Sets Stage to the given stage name and returns this patch for chaining.
---@param stage string The stage to schedule the patch in.
---@return LuaPatch self This patch.
function LuaPatch:OnStage(stage) end

---The PatchManager Lua library, exposed to scripts as the global `PM`.
---@type PatchManagerCore
PM = nil

---Lua module exposed under the global `J` namespace, providing helpers for constructing JSON literals
---that MoonSharp's auto-conversion does not produce.
---@type JsonModule
J = nil

---The mod ID; exposed to scripts as the `ModId` global and used as their default stage.
---@type string
ModId = nil

---The directory the patch was discovered in; exposed to the script as the `Location` global.
---@type string?
Location = nil
