//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/arall/PatchManager/src/PatchManager.SassyPatching/SassyPatchGrammar\sassy_parser.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SassyPatchGrammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="sassy_parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface Isassy_parserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.patch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatch([NotNull] sassy_parser.PatchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.patch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatch([NotNull] sassy_parser.PatchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_statement([NotNull] sassy_parser.Top_level_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_statement([NotNull] sassy_parser.Top_level_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.patch_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatch_declaration([NotNull] sassy_parser.Patch_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.patch_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatch_declaration([NotNull] sassy_parser.Patch_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.patch_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatch_list([NotNull] sassy_parser.Patch_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.patch_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatch_list([NotNull] sassy_parser.Patch_listContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>quoted_string</c>
	/// labeled alternative in <see cref="sassy_parser.sassy_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuoted_string([NotNull] sassy_parser.Quoted_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>quoted_string</c>
	/// labeled alternative in <see cref="sassy_parser.sassy_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuoted_string([NotNull] sassy_parser.Quoted_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unquoted_string</c>
	/// labeled alternative in <see cref="sassy_parser.sassy_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnquoted_string([NotNull] sassy_parser.Unquoted_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unquoted_string</c>
	/// labeled alternative in <see cref="sassy_parser.sassy_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnquoted_string([NotNull] sassy_parser.Unquoted_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.import_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_declaration([NotNull] sassy_parser.Import_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.import_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_declaration([NotNull] sassy_parser.Import_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>normal_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormal_var_decl([NotNull] sassy_parser.Normal_var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>normal_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormal_var_decl([NotNull] sassy_parser.Normal_var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>add_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_var_decl([NotNull] sassy_parser.Add_var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>add_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_var_decl([NotNull] sassy_parser.Add_var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>subtract_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubtract_var_decl([NotNull] sassy_parser.Subtract_var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>subtract_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubtract_var_decl([NotNull] sassy_parser.Subtract_var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>divide_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivide_var_decl([NotNull] sassy_parser.Divide_var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>divide_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivide_var_decl([NotNull] sassy_parser.Divide_var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multiply_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiply_var_decl([NotNull] sassy_parser.Multiply_var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multiply_var_decl</c>
	/// labeled alternative in <see cref="sassy_parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiply_var_decl([NotNull] sassy_parser.Multiply_var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>implicit_stage_def</c>
	/// labeled alternative in <see cref="sassy_parser.stage_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicit_stage_def([NotNull] sassy_parser.Implicit_stage_defContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>implicit_stage_def</c>
	/// labeled alternative in <see cref="sassy_parser.stage_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicit_stage_def([NotNull] sassy_parser.Implicit_stage_defContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>global_stage_def</c>
	/// labeled alternative in <see cref="sassy_parser.stage_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobal_stage_def([NotNull] sassy_parser.Global_stage_defContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>global_stage_def</c>
	/// labeled alternative in <see cref="sassy_parser.stage_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobal_stage_def([NotNull] sassy_parser.Global_stage_defContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>relative_stage_def</c>
	/// labeled alternative in <see cref="sassy_parser.stage_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelative_stage_def([NotNull] sassy_parser.Relative_stage_defContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>relative_stage_def</c>
	/// labeled alternative in <see cref="sassy_parser.stage_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelative_stage_def([NotNull] sassy_parser.Relative_stage_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.config_creation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConfig_creation([NotNull] sassy_parser.Config_creationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.config_creation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConfig_creation([NotNull] sassy_parser.Config_creationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>update_config_full</c>
	/// labeled alternative in <see cref="sassy_parser.config_mutation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate_config_full([NotNull] sassy_parser.Update_config_fullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>update_config_full</c>
	/// labeled alternative in <see cref="sassy_parser.config_mutation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate_config_full([NotNull] sassy_parser.Update_config_fullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>update_config_label</c>
	/// labeled alternative in <see cref="sassy_parser.config_mutation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate_config_label([NotNull] sassy_parser.Update_config_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>update_config_label</c>
	/// labeled alternative in <see cref="sassy_parser.config_mutation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate_config_label([NotNull] sassy_parser.Update_config_labelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stage_value_before</c>
	/// labeled alternative in <see cref="sassy_parser.stage_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStage_value_before([NotNull] sassy_parser.Stage_value_beforeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stage_value_before</c>
	/// labeled alternative in <see cref="sassy_parser.stage_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStage_value_before([NotNull] sassy_parser.Stage_value_beforeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stage_value_after</c>
	/// labeled alternative in <see cref="sassy_parser.stage_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStage_value_after([NotNull] sassy_parser.Stage_value_afterContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stage_value_after</c>
	/// labeled alternative in <see cref="sassy_parser.stage_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStage_value_after([NotNull] sassy_parser.Stage_value_afterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.function_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_def([NotNull] sassy_parser.Function_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.function_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_def([NotNull] sassy_parser.Function_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.mixin_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMixin_def([NotNull] sassy_parser.Mixin_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.mixin_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMixin_def([NotNull] sassy_parser.Mixin_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_conditional([NotNull] sassy_parser.Top_level_conditionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_conditional([NotNull] sassy_parser.Top_level_conditionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_else([NotNull] sassy_parser.Top_level_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_else([NotNull] sassy_parser.Top_level_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_else_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_else_else([NotNull] sassy_parser.Top_level_else_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_else_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_else_else([NotNull] sassy_parser.Top_level_else_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_else_if([NotNull] sassy_parser.Top_level_else_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_else_if([NotNull] sassy_parser.Top_level_else_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.selection_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection_block([NotNull] sassy_parser.Selection_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.selection_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection_block([NotNull] sassy_parser.Selection_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.attributed_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributed_selector([NotNull] sassy_parser.Attributed_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.attributed_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributed_selector([NotNull] sassy_parser.Attributed_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>require_mod</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequire_mod([NotNull] sassy_parser.Require_modContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>require_mod</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequire_mod([NotNull] sassy_parser.Require_modContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>run_at_stage</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRun_at_stage([NotNull] sassy_parser.Run_at_stageContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>run_at_stage</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRun_at_stage([NotNull] sassy_parser.Run_at_stageContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>new_asset</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNew_asset([NotNull] sassy_parser.New_assetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>new_asset</c>
	/// labeled alternative in <see cref="sassy_parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNew_asset([NotNull] sassy_parser.New_assetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.constructor_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructor_arguments([NotNull] sassy_parser.Constructor_argumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.constructor_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructor_arguments([NotNull] sassy_parser.Constructor_argumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_class_capture</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_class_capture([NotNull] sassy_parser.Sel_class_captureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_class_capture</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_class_capture([NotNull] sassy_parser.Sel_class_captureContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_child</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_child([NotNull] sassy_parser.Sel_childContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_child</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_child([NotNull] sassy_parser.Sel_childContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_class([NotNull] sassy_parser.Sel_classContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_class([NotNull] sassy_parser.Sel_classContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_name([NotNull] sassy_parser.Sel_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_name([NotNull] sassy_parser.Sel_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_intersection</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_intersection([NotNull] sassy_parser.Sel_intersectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_intersection</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_intersection([NotNull] sassy_parser.Sel_intersectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_string_class_capture</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_string_class_capture([NotNull] sassy_parser.Sel_string_class_captureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_string_class_capture</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_string_class_capture([NotNull] sassy_parser.Sel_string_class_captureContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_ensure</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_ensure([NotNull] sassy_parser.Sel_ensureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_ensure</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_ensure([NotNull] sassy_parser.Sel_ensureContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_everything([NotNull] sassy_parser.Sel_everythingContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_everything([NotNull] sassy_parser.Sel_everythingContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_without_string_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_without_string_class([NotNull] sassy_parser.Sel_without_string_classContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_without_string_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_without_string_class([NotNull] sassy_parser.Sel_without_string_classContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_string_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_string_class([NotNull] sassy_parser.Sel_string_classContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_string_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_string_class([NotNull] sassy_parser.Sel_string_classContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_string_name([NotNull] sassy_parser.Sel_string_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_string_name([NotNull] sassy_parser.Sel_string_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_element([NotNull] sassy_parser.Sel_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_element([NotNull] sassy_parser.Sel_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_ruleset</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_ruleset([NotNull] sassy_parser.Sel_rulesetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_ruleset</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_ruleset([NotNull] sassy_parser.Sel_rulesetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_add_element([NotNull] sassy_parser.Sel_add_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_add_element([NotNull] sassy_parser.Sel_add_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_element_string</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_element_string([NotNull] sassy_parser.Sel_element_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_element_string</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_element_string([NotNull] sassy_parser.Sel_element_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_add_string_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_add_string_element([NotNull] sassy_parser.Sel_add_string_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_add_string_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_add_string_element([NotNull] sassy_parser.Sel_add_string_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_without_string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_without_string_name([NotNull] sassy_parser.Sel_without_string_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_without_string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_without_string_name([NotNull] sassy_parser.Sel_without_string_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_without_class([NotNull] sassy_parser.Sel_without_classContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_without_class([NotNull] sassy_parser.Sel_without_classContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_string_ensure</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_string_ensure([NotNull] sassy_parser.Sel_string_ensureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_string_ensure</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_string_ensure([NotNull] sassy_parser.Sel_string_ensureContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_without_name([NotNull] sassy_parser.Sel_without_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_without_name([NotNull] sassy_parser.Sel_without_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_combination</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_combination([NotNull] sassy_parser.Sel_combinationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_combination</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_combination([NotNull] sassy_parser.Sel_combinationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_sub</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_sub([NotNull] sassy_parser.Sel_subContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_sub</c>
	/// labeled alternative in <see cref="sassy_parser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_sub([NotNull] sassy_parser.Sel_subContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ruleset_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleset_selector([NotNull] sassy_parser.Ruleset_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ruleset_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleset_selector([NotNull] sassy_parser.Ruleset_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_class_capture_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_class_capture_selector([NotNull] sassy_parser.String_class_capture_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_class_capture_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_class_capture_selector([NotNull] sassy_parser.String_class_capture_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>without_string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithout_string_name([NotNull] sassy_parser.Without_string_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>without_string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithout_string_name([NotNull] sassy_parser.Without_string_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sub_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSub_selector([NotNull] sassy_parser.Sub_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sub_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSub_selector([NotNull] sassy_parser.Sub_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>class_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_selector([NotNull] sassy_parser.Class_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>class_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_selector([NotNull] sassy_parser.Class_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithout_class([NotNull] sassy_parser.Without_classContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>without_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithout_class([NotNull] sassy_parser.Without_classContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_name([NotNull] sassy_parser.String_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_name([NotNull] sassy_parser.String_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_class_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_class_selector([NotNull] sassy_parser.String_class_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_class_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_class_selector([NotNull] sassy_parser.String_class_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>add_string_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_string_element([NotNull] sassy_parser.Add_string_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>add_string_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_string_element([NotNull] sassy_parser.Add_string_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>combination_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCombination_selector([NotNull] sassy_parser.Combination_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>combination_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCombination_selector([NotNull] sassy_parser.Combination_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>class_capture_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_capture_selector([NotNull] sassy_parser.Class_capture_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>class_capture_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_capture_selector([NotNull] sassy_parser.Class_capture_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithout_name([NotNull] sassy_parser.Without_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>without_name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithout_name([NotNull] sassy_parser.Without_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] sassy_parser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>name</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] sassy_parser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_element([NotNull] sassy_parser.Add_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>add_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_element([NotNull] sassy_parser.Add_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>without_string_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithout_string_class([NotNull] sassy_parser.Without_string_classContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>without_string_class</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithout_string_class([NotNull] sassy_parser.Without_string_classContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEverything([NotNull] sassy_parser.EverythingContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>everything</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEverything([NotNull] sassy_parser.EverythingContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>intersection_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntersection_selector([NotNull] sassy_parser.Intersection_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>intersection_selector</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntersection_selector([NotNull] sassy_parser.Intersection_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_element([NotNull] sassy_parser.String_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_element([NotNull] sassy_parser.String_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] sassy_parser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>element</c>
	/// labeled alternative in <see cref="sassy_parser.selector_no_children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] sassy_parser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.selector_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector_body([NotNull] sassy_parser.Selector_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.selector_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector_body([NotNull] sassy_parser.Selector_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.selector_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector_statement([NotNull] sassy_parser.Selector_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.selector_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector_statement([NotNull] sassy_parser.Selector_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_conditional([NotNull] sassy_parser.Sel_level_conditionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_conditional([NotNull] sassy_parser.Sel_level_conditionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_else([NotNull] sassy_parser.Sel_level_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_else([NotNull] sassy_parser.Sel_level_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_else_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_else_else([NotNull] sassy_parser.Sel_level_else_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_else_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_else_else([NotNull] sassy_parser.Sel_level_else_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_else_if([NotNull] sassy_parser.Sel_level_else_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_else_if([NotNull] sassy_parser.Sel_level_else_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.set_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_value([NotNull] sassy_parser.Set_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.set_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_value([NotNull] sassy_parser.Set_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.delete_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelete_value([NotNull] sassy_parser.Delete_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.delete_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelete_value([NotNull] sassy_parser.Delete_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.merge_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMerge_value([NotNull] sassy_parser.Merge_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.merge_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMerge_value([NotNull] sassy_parser.Merge_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>normal_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormal_field_set([NotNull] sassy_parser.Normal_field_setContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>normal_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormal_field_set([NotNull] sassy_parser.Normal_field_setContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>add_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_field_set([NotNull] sassy_parser.Add_field_setContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>add_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_field_set([NotNull] sassy_parser.Add_field_setContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>subtract_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubtract_field_set([NotNull] sassy_parser.Subtract_field_setContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>subtract_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubtract_field_set([NotNull] sassy_parser.Subtract_field_setContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multiply_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiply_field_set([NotNull] sassy_parser.Multiply_field_setContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multiply_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiply_field_set([NotNull] sassy_parser.Multiply_field_setContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>divide_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivide_field_set([NotNull] sassy_parser.Divide_field_setContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>divide_field_set</c>
	/// labeled alternative in <see cref="sassy_parser.field_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivide_field_set([NotNull] sassy_parser.Divide_field_setContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>number_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_indexor([NotNull] sassy_parser.Number_indexorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>number_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_indexor([NotNull] sassy_parser.Number_indexorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>element_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement_indexor([NotNull] sassy_parser.Element_indexorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>element_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement_indexor([NotNull] sassy_parser.Element_indexorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>class_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_indexor([NotNull] sassy_parser.Class_indexorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>class_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_indexor([NotNull] sassy_parser.Class_indexorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_indexor([NotNull] sassy_parser.String_indexorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_indexor</c>
	/// labeled alternative in <see cref="sassy_parser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_indexor([NotNull] sassy_parser.String_indexorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>not_equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot_equal_to([NotNull] sassy_parser.Not_equal_toContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>not_equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot_equal_to([NotNull] sassy_parser.Not_equal_toContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_reference([NotNull] sassy_parser.Variable_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_reference([NotNull] sassy_parser.Variable_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqual_to([NotNull] sassy_parser.Equal_toContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>equal_to</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqual_to([NotNull] sassy_parser.Equal_toContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>local_variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_variable_reference([NotNull] sassy_parser.Local_variable_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>local_variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_variable_reference([NotNull] sassy_parser.Local_variable_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>member_call_ruleset</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_call_ruleset([NotNull] sassy_parser.Member_call_rulesetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>member_call_ruleset</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_call_ruleset([NotNull] sassy_parser.Member_call_rulesetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>value_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_reference([NotNull] sassy_parser.Value_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>value_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_reference([NotNull] sassy_parser.Value_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>subtraction</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubtraction([NotNull] sassy_parser.SubtractionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>subtraction</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubtraction([NotNull] sassy_parser.SubtractionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivision([NotNull] sassy_parser.DivisionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivision([NotNull] sassy_parser.DivisionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>negative</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegative([NotNull] sassy_parser.NegativeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>negative</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegative([NotNull] sassy_parser.NegativeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>not</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot([NotNull] sassy_parser.NotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>not</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot([NotNull] sassy_parser.NotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lesser_than</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLesser_than([NotNull] sassy_parser.Lesser_thanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lesser_than</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLesser_than([NotNull] sassy_parser.Lesser_thanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>member_call</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_call([NotNull] sassy_parser.Member_callContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>member_call</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_call([NotNull] sassy_parser.Member_callContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>greater_than</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreater_than([NotNull] sassy_parser.Greater_thanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>greater_than</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreater_than([NotNull] sassy_parser.Greater_thanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd([NotNull] sassy_parser.AndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd([NotNull] sassy_parser.AndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sub_sub_expression</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSub_sub_expression([NotNull] sassy_parser.Sub_sub_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sub_sub_expression</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSub_sub_expression([NotNull] sassy_parser.Sub_sub_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multiplication</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplication([NotNull] sassy_parser.MultiplicationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multiplication</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplication([NotNull] sassy_parser.MultiplicationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>greater_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreater_than_equal([NotNull] sassy_parser.Greater_than_equalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>greater_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreater_than_equal([NotNull] sassy_parser.Greater_than_equalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>addition</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddition([NotNull] sassy_parser.AdditionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>addition</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddition([NotNull] sassy_parser.AdditionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>indexor</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexor([NotNull] sassy_parser.IndexorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>indexor</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexor([NotNull] sassy_parser.IndexorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr([NotNull] sassy_parser.OrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr([NotNull] sassy_parser.OrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lesser_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLesser_than_equal([NotNull] sassy_parser.Lesser_than_equalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lesser_than_equal</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLesser_than_equal([NotNull] sassy_parser.Lesser_than_equalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>positive</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPositive([NotNull] sassy_parser.PositiveContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>positive</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPositive([NotNull] sassy_parser.PositiveContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>simple_call</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_call([NotNull] sassy_parser.Simple_callContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>simple_call</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_call([NotNull] sassy_parser.Simple_callContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_local_variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_local_variable_reference([NotNull] sassy_parser.String_local_variable_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_local_variable_reference</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_local_variable_reference([NotNull] sassy_parser.String_local_variable_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>remainder</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemainder([NotNull] sassy_parser.RemainderContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>remainder</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemainder([NotNull] sassy_parser.RemainderContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ternary</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTernary([NotNull] sassy_parser.TernaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ternary</c>
	/// labeled alternative in <see cref="sassy_parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTernary([NotNull] sassy_parser.TernaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>value_deletion</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_deletion([NotNull] sassy_parser.Value_deletionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>value_deletion</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_deletion([NotNull] sassy_parser.Value_deletionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boolean_true</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_true([NotNull] sassy_parser.Boolean_trueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolean_true</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_true([NotNull] sassy_parser.Boolean_trueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boolean_false</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_false([NotNull] sassy_parser.Boolean_falseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolean_false</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_false([NotNull] sassy_parser.Boolean_falseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>number_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_value([NotNull] sassy_parser.Number_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>number_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_value([NotNull] sassy_parser.Number_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_value([NotNull] sassy_parser.String_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_value([NotNull] sassy_parser.String_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>element_string</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement_string([NotNull] sassy_parser.Element_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>element_string</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement_string([NotNull] sassy_parser.Element_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>none</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNone([NotNull] sassy_parser.NoneContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>none</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNone([NotNull] sassy_parser.NoneContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>closure</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClosure([NotNull] sassy_parser.ClosureContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>closure</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClosure([NotNull] sassy_parser.ClosureContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>list_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_value([NotNull] sassy_parser.List_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>list_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_value([NotNull] sassy_parser.List_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>object_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_value([NotNull] sassy_parser.Object_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>object_value</c>
	/// labeled alternative in <see cref="sassy_parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_value([NotNull] sassy_parser.Object_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>require_sub</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequire_sub([NotNull] sassy_parser.Require_subContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>require_sub</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequire_sub([NotNull] sassy_parser.Require_subContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>require_or</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequire_or([NotNull] sassy_parser.Require_orContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>require_or</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequire_or([NotNull] sassy_parser.Require_orContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>require_not</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequire_not([NotNull] sassy_parser.Require_notContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>require_not</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequire_not([NotNull] sassy_parser.Require_notContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>require_guid</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequire_guid([NotNull] sassy_parser.Require_guidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>require_guid</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequire_guid([NotNull] sassy_parser.Require_guidContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>require_and</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequire_and([NotNull] sassy_parser.Require_andContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>require_and</c>
	/// labeled alternative in <see cref="sassy_parser.require_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequire_and([NotNull] sassy_parser.Require_andContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] sassy_parser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] sassy_parser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.list_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_values([NotNull] sassy_parser.List_valuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.list_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_values([NotNull] sassy_parser.List_valuesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj([NotNull] sassy_parser.ObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj([NotNull] sassy_parser.ObjContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.obj_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj_values([NotNull] sassy_parser.Obj_valuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.obj_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj_values([NotNull] sassy_parser.Obj_valuesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>literal_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral_key([NotNull] sassy_parser.Literal_keyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>literal_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral_key([NotNull] sassy_parser.Literal_keyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_key([NotNull] sassy_parser.String_keyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string_key</c>
	/// labeled alternative in <see cref="sassy_parser.key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_key([NotNull] sassy_parser.String_keyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_list([NotNull] sassy_parser.Argument_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_list([NotNull] sassy_parser.Argument_listContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>named_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamed_argument([NotNull] sassy_parser.Named_argumentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>named_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamed_argument([NotNull] sassy_parser.Named_argumentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unnamed_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnnamed_argument([NotNull] sassy_parser.Unnamed_argumentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unnamed_argument</c>
	/// labeled alternative in <see cref="sassy_parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnnamed_argument([NotNull] sassy_parser.Unnamed_argumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.arg_decl_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg_decl_list([NotNull] sassy_parser.Arg_decl_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.arg_decl_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg_decl_list([NotNull] sassy_parser.Arg_decl_listContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>argument_without_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_without_default([NotNull] sassy_parser.Argument_without_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>argument_without_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_without_default([NotNull] sassy_parser.Argument_without_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>argument_with_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_with_default([NotNull] sassy_parser.Argument_with_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>argument_with_default</c>
	/// labeled alternative in <see cref="sassy_parser.arg_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_with_default([NotNull] sassy_parser.Argument_with_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] sassy_parser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] sassy_parser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_statement([NotNull] sassy_parser.Function_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_statement([NotNull] sassy_parser.Function_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFn_level_conditional([NotNull] sassy_parser.Fn_level_conditionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFn_level_conditional([NotNull] sassy_parser.Fn_level_conditionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFn_level_else([NotNull] sassy_parser.Fn_level_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFn_level_else([NotNull] sassy_parser.Fn_level_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_else_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFn_level_else_else([NotNull] sassy_parser.Fn_level_else_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_else_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFn_level_else_else([NotNull] sassy_parser.Fn_level_else_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_level_else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFn_level_else_if([NotNull] sassy_parser.Fn_level_else_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_level_else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFn_level_else_if([NotNull] sassy_parser.Fn_level_else_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.fn_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFn_return([NotNull] sassy_parser.Fn_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.fn_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFn_return([NotNull] sassy_parser.Fn_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.mixin_include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMixin_include([NotNull] sassy_parser.Mixin_includeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.mixin_include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMixin_include([NotNull] sassy_parser.Mixin_includeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>for_to_loop</c>
	/// labeled alternative in <see cref="sassy_parser.for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_to_loop([NotNull] sassy_parser.For_to_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>for_to_loop</c>
	/// labeled alternative in <see cref="sassy_parser.for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_to_loop([NotNull] sassy_parser.For_to_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>for_through_loop</c>
	/// labeled alternative in <see cref="sassy_parser.for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_through_loop([NotNull] sassy_parser.For_through_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>for_through_loop</c>
	/// labeled alternative in <see cref="sassy_parser.for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_through_loop([NotNull] sassy_parser.For_through_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>top_level_for_to_loop</c>
	/// labeled alternative in <see cref="sassy_parser.top_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_for_to_loop([NotNull] sassy_parser.Top_level_for_to_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>top_level_for_to_loop</c>
	/// labeled alternative in <see cref="sassy_parser.top_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_for_to_loop([NotNull] sassy_parser.Top_level_for_to_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>top_level_for_through_loop</c>
	/// labeled alternative in <see cref="sassy_parser.top_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_for_through_loop([NotNull] sassy_parser.Top_level_for_through_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>top_level_for_through_loop</c>
	/// labeled alternative in <see cref="sassy_parser.top_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_for_through_loop([NotNull] sassy_parser.Top_level_for_through_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_level_for_to_loop</c>
	/// labeled alternative in <see cref="sassy_parser.sel_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_for_to_loop([NotNull] sassy_parser.Sel_level_for_to_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_level_for_to_loop</c>
	/// labeled alternative in <see cref="sassy_parser.sel_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_for_to_loop([NotNull] sassy_parser.Sel_level_for_to_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sel_level_for_through_loop</c>
	/// labeled alternative in <see cref="sassy_parser.sel_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_for_through_loop([NotNull] sassy_parser.Sel_level_for_through_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sel_level_for_through_loop</c>
	/// labeled alternative in <see cref="sassy_parser.sel_level_for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_for_through_loop([NotNull] sassy_parser.Sel_level_for_through_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.each_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEach_loop([NotNull] sassy_parser.Each_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.each_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEach_loop([NotNull] sassy_parser.Each_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_each_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_each_loop([NotNull] sassy_parser.Top_level_each_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_each_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_each_loop([NotNull] sassy_parser.Top_level_each_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_each_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_each_loop([NotNull] sassy_parser.Sel_level_each_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_each_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_each_loop([NotNull] sassy_parser.Sel_level_each_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_loop([NotNull] sassy_parser.While_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_loop([NotNull] sassy_parser.While_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.top_level_while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_while_loop([NotNull] sassy_parser.Top_level_while_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.top_level_while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_while_loop([NotNull] sassy_parser.Top_level_while_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sassy_parser.sel_level_while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel_level_while_loop([NotNull] sassy_parser.Sel_level_while_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sassy_parser.sel_level_while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel_level_while_loop([NotNull] sassy_parser.Sel_level_while_loopContext context);
}
} // namespace SassyPatchGrammar
